package com.oocode

import com.oneeyedmen.okeydoke.Approver
import com.oneeyedmen.okeydoke.junit5.ApprovalsExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.RegisterExtension
import java.io.File

class ExampleApprovalTest {
    @RegisterExtension
    public var approvals = ApprovalsExtension(File("src/test/resources/approval"))

    @Test
    fun canDoAnApproval(approver: Approver) {
        approver.assertApproved("Some text generated by the system under test")
    }
}
